apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: strapi
  name: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strapi
    spec:
      containers:
      - image: oelyhasina/images:serversi-1  # Remplacez par votre image Strapi
        name: strapi
        env:
         - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "1337"
        - name: APP_KEYS
          valueFrom:
            secretKeyRef:
              name: strapi-secret
              key: app-keys
        - name: API_TOKEN_SALT
          valueFrom:
            secretKeyRef:
              name: strapi-secret
              key: app-token-salt
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: strapi-secret
              key: admin-jwt-secret
        - name: TRANSFER_TOKEN_SALT
          valueFrom:
            secretKeyRef:
              name: strapi-secret
              key: transfert-token-salt
        # Database
        - name: DATABASE_CLIENT
          value: "postgres"
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: strapi-secret
              key: database-host
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: strapi-secret
              key: database-port
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: strapi-secret
              key: database-name
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: strapi-secret
              key: database-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: strapi-secret
              key: database-password
        - name: DATABASE_SSL
          value: "false"  # ou "true" si SSL est utilisé
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: strapi-secret
              key: jwt-secret
        resources: {}
        ports:
        - containerPort: 1337
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: strapi-service
  labels:
    app: strapi-service
spec:
  type: NodePort
  ports:
  - nodePort: 30002  # Vous pouvez changer le nodePort si nécessaire
    port: 80
    targetPort: 1337  # Port sur lequel Strapi est exposé
  selector:
    app: strapi
